version: "3.3"
services:
  # Postgres *****************************************
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=springuser
      - POSTGRES_PASSWORD=springuser
      - POSTGRES_DB=adidas_challenge
    restart: unless-stopped
  # Server *****************************************
  citiesserver:
    image: citiesserver:latest
    container_name: citiesserver
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - postgres
  # Client *****************************************
  citiesclient:
    image: citiesclient:latest
    container_name: citiesclient
    ports:
      - 9091:9091
    restart: unless-stopped
    depends_on:
      - citiesserver
